releaseに向けて細かい手直し
one-scope/multi-post pull request #1
Opened 2023-06-19 09:53 UTC by okuda2107

- 投稿内容が指定されてない場合エラー表示されるようにした．
- configを読み込むファイルをオプションで指定できるようにした．
- 存在しないchannelが指定されたときにエラー表示されるようにした．
- configファイルにないchannelsが指定されたときにエラー表示されるようにした．

2023-06-30 05:12 UTC, earlgray283 requested changes

2023-06-30 05:12 UTC, earlgray283 commented on main.go
> +	tChannels, tOK := tConfig.Groups[*tGroup]
tGroups ではないですか？ :eyes:

2023-06-30 05:12 UTC, earlgray283 commented on config.go
> +	Services map[string]service `yaml:"services"` //大文字じゃないとダメ
[nits] 指摘漏れでしたが、map の変数はなるべくそれが map であることを分かるようにした方が良さそうです。
僕の場合だと `ValueByKey` みたいな命名をすることが多くて、今回の場合だと `ChannelsByID` みたいにします(もちろんこの限りではないので別でも大丈夫です 🙆‍♂️ )

2023-06-30 05:12 UTC, earlgray283 commented on config.go
> +	Services map[string]service `yaml:"services"` //大文字じゃないとダメ
[imo] 「大文字じゃないとダメ」は自明みたいな部分があるので、削除しちゃっても大丈夫だと思います(僕も結構自明なコメントをやりがちです・・)

2023-06-30 05:18 UTC, earlgray283 requested changes

2023-06-30 05:18 UTC, earlgray283 commented on config.go
> +var ServiceMap = make(map[string]Bot)
[q] ServiceMap のスコープをグローバルにしたのって何か意図はあったりしますか？

2023-06-30 05:18 UTC, earlgray283 commented on main.go
> +	VERSION = "Version 1.0.0"
VERSION は const 値にしちゃって良い気がします

2023-06-30 05:18 UTC, earlgray283 commented on main.go
> +	VERSION = "Version 1.0.0"
[nits] 原則として Go の命名規則は camelCase と PascalCase のどちらかだけなので、今回は version とかにした方が良さそうです。例外として `os.O_RDONLY` とかありますが、これは posix の O_RDONLY と同一のものになっているので例外となります。
https://stackoverflow.com/questions/22688906/go-naming-conventions-for-const

2023-07-02 06:10 UTC, okuda2107 commented on main.go
> +	tChannels, tOK := tConfig.Groups[*tGroup]
いえ，これは引数で受け取ったチャンネルが存在するかを確認しにいっているのでtGroupで大丈夫です．と思いましたが，下の投稿処理とスコープが違いますが，名前が被っているので変更しました．ありがとうございます．

2023-07-03 10:07 UTC, earlgray283 commented on config.go
> +var botByServiceName = make(map[string]Bot)
[q] botByServiceName のスコープは main 関数内だけで良い気がするんですが、グローバル変数にしているのは何か意図があったりしますか？

2023-07-03 10:10 UTC, earlgray283 commented on main.go
> +	tChannels, tOK := tConfig.GroupByID[*tGroupID]
[q] ここは tChannels ではなく tGroups の方が命名的に適している気がするのですがどうでしょうか？64 行目でもループ変数の名前が tGroup になっているので :eyes:

2023-07-10 10:36 UTC, earlgray283 approved these changes
LGTM です 🙆‍♂️

2023-07-10 10:42 UTC, merged